"""Service-layer modules for the backend application."""

from app.services.assets import (
    AssetNotFoundError,
    AssetServiceError,
    InvalidAssetPathError,
    InvalidAssetDirectoryError,
    InvalidAssetUploadError,
    infer_file_type,
    inspect_asset_path,
    normalize_asset_path,
    normalize_uploaded_file_name,
)
from app.services.conversions import (
    ConversionExecutionError,
    ConversionNotFoundError,
    ConversionService,
    ConversionServiceError,
    ConversionValidationError,
    get_conversion,
    get_conversion_or_raise,
    list_conversions,
)
from app.services.episodes import (
    EpisodeDiscoveryUnavailableError,
    EpisodeNotFoundError,
    EpisodePlaybackError,
    EpisodeStreamNotFoundError,
    get_episode_detail,
    get_episode_samples,
    get_episode_timeline,
    open_asset_reader,
)
from app.services.jobs import (
    JobNotFoundError,
    JobService,
    JobServiceError,
    JobStateTransitionError,
    get_job,
    get_job_or_raise,
    list_jobs as list_tracked_jobs,
)
from app.services.output_actions import (
    OutputActionNotFoundError,
    OutputActionService,
    OutputActionServiceError,
    OutputActionValidationError,
    get_output_action,
    get_output_action_or_raise,
    list_output_actions_for_output,
)
from app.services.visualization import (
    VisualizationError,
    VisualizationGenerationError,
    VisualizationNotFoundError,
    VisualizationService,
)

__all__ = [
    "ConversionExecutionError",
    "ConversionNotFoundError",
    "ConversionService",
    "ConversionServiceError",
    "ConversionValidationError",
    "AssetNotFoundError",
    "AssetServiceError",
    "EpisodeDiscoveryUnavailableError",
    "EpisodeNotFoundError",
    "EpisodePlaybackError",
    "EpisodeStreamNotFoundError",
    "InvalidAssetDirectoryError",
    "InvalidAssetPathError",
    "InvalidAssetUploadError",
    "JobNotFoundError",
    "JobService",
    "JobServiceError",
    "JobStateTransitionError",
    "OutputActionNotFoundError",
    "OutputActionService",
    "OutputActionServiceError",
    "OutputActionValidationError",
    "VisualizationError",
    "VisualizationGenerationError",
    "VisualizationNotFoundError",
    "VisualizationService",
    "get_conversion",
    "get_conversion_or_raise",
    "get_episode_detail",
    "get_episode_samples",
    "get_episode_timeline",
    "get_job",
    "get_job_or_raise",
    "get_output_action",
    "get_output_action_or_raise",
    "infer_file_type",
    "inspect_asset_path",
    "list_conversions",
    "list_output_actions_for_output",
    "list_tracked_jobs",
    "normalize_asset_path",
    "normalize_uploaded_file_name",
    "open_asset_reader",
]
