"""Service-layer modules for the backend application."""

from backend.app.services.assets import (
    AssetAlreadyRegisteredError,
    AssetNotFoundError,
    AssetServiceError,
    InspectedAssetPath,
    InvalidAssetPathError,
    get_asset,
    get_asset_or_raise,
    infer_file_type,
    inspect_asset_path,
    list_assets,
    normalize_asset_path,
    register_asset,
)
from backend.app.services.conversions import (
    ConversionExecutionError,
    ConversionNotFoundError,
    ConversionService,
    ConversionServiceError,
    ConversionValidationError,
    get_conversion,
    get_conversion_or_raise,
    list_conversions,
)
from backend.app.services.indexing import AssetIndexingError, IndexingService, ReindexAllResult
from backend.app.services.jobs import (
    JobNotFoundError,
    JobService,
    JobServiceError,
    JobStateTransitionError,
    get_job,
    get_job_or_raise,
    list_jobs as list_tracked_jobs,
)
from backend.app.services.tags import (
    AssetTagAlreadyExistsError,
    AssetTagNotFoundError,
    TagAlreadyExistsError,
    TagNotFoundError,
    TagServiceError,
    attach_tag_to_asset,
    create_tag,
    get_tag,
    get_tag_or_raise,
    list_tags,
    normalize_tag_name,
    remove_tag_from_asset,
)

__all__ = [
    "AssetAlreadyRegisteredError",
    "ConversionExecutionError",
    "ConversionNotFoundError",
    "ConversionService",
    "ConversionServiceError",
    "ConversionValidationError",
    "AssetIndexingError",
    "AssetNotFoundError",
    "AssetServiceError",
    "AssetTagAlreadyExistsError",
    "AssetTagNotFoundError",
    "InspectedAssetPath",
    "IndexingService",
    "InvalidAssetPathError",
    "JobNotFoundError",
    "JobService",
    "JobServiceError",
    "JobStateTransitionError",
    "ReindexAllResult",
    "TagAlreadyExistsError",
    "TagNotFoundError",
    "TagServiceError",
    "attach_tag_to_asset",
    "create_tag",
    "get_asset",
    "get_asset_or_raise",
    "get_conversion",
    "get_conversion_or_raise",
    "get_job",
    "get_job_or_raise",
    "get_tag",
    "get_tag_or_raise",
    "infer_file_type",
    "inspect_asset_path",
    "list_assets",
    "list_conversions",
    "list_tracked_jobs",
    "list_tags",
    "normalize_asset_path",
    "normalize_tag_name",
    "register_asset",
    "remove_tag_from_asset",
]
